### PR TITLE
WIP: pangeify

### PR DESCRIPTION
**Pull request by delgadom**
## Workflow

* [x] Closes issues #77, #80, #82, #83, #87, #92, #99
* [x] Passes travis tests
* [x] Image deployed on `dev` branch (see [notebook](https://hub.docker.com/r/rhodium/notebook/tags/) and [worker](https://hub.docker.com/r/rhodium/worker/tags/) dev tags)
* [ ] Worker passes manual deployment test on compute.rhg (not sure this can pass)
* [x] Notebook+worker passes test-cluster deployment with new user
* [x] Notebook+worker passes test-hub deployment with existing users
* [x] Updates integrated into downstream images:
  * [x] octave
  * [x] pytc
  * [x] emanuel

Special to-dos for this PR:

* [x] Should also address (but does not currently) #95
* [ ] Check to make sure modifying the environment file modifies the docker image and hash when pulling from a cached dev container with no other changes
* [x] Make sure we can upgrade the cluster without deleting user directories or anything else important. The helm chart updates have some pretty significant breaking changes, and involve force-upgrading the cluster and deleting some services. See jupyterhub/zero-to-jupyterhub-k8s#638
* [ ] Make sure geopandas is still vectorized. To solve the packages in this release, I switched from the `conda-forge/label/dev::geopandas` to simply `conda-forge::geopandas`. The label/dev version was the recommended method for installing the cythonized version of geopandas, but I am honestly not sure what is anymore. If this is not vectorized, this will render geopandas unusable for many of our applications.
* [ ] pin package versions so we can ensure this image can be built in the future
* [ ] maybe pin helm chart dependencies rather than using inequalities?
* [x] make sure workers scale down effectively
* [x] make sure autocomplete doesn't return everything under the sun (look at jedi, tornado issues)
* [ ] make sure distributed.progress bar works (seems to be having issues)

Down the line:

* [ ] Once this is merged & deployed on all servers, we should file an issue to update our jupyterlab templates (see RhodiumGroup/rhodium-custom-jupyterhub-templates#1). This would break the current deployment since the template repo structure has changed significantly since the version of jupyterhub currently deployed. If we can figure out how to deploy templates from a [templates repo branch in the helm chart](https://github.com/RhodiumGroup/helm-chart/blob/master/jupyter-config.yml#L67) we could test changes before deployment.

## Summary

Depends on corresponding helm-chart PR RhodiumGroup/helm-chart#6

Rolled back cluster to v0.2.5 tag, then unpinned all packages and allowed conda to freely solve the spec. This undoes a number of upgrades we have made to the cluster since v0.2.5, which will have to be re-introduced in this PR or after this is merged. The current master branch was forcibly rolled back to tag v0.2.5. The previous version of the master branch is stashed on the branch `master-stash`. The versions of jupyterhub, jupyterlab, notebook, dask, and many plotting/viz libraries in this PR are incompatible with the helm chart and jupyterhub image used in the current cluster, so a corresponding update to our helm chart and its dependencies had to be made in order for this image to be deployed.

### Helm chart PR updates

* helm chart dependencies (jupyterhub >= 0.8.2)
* jupyterhub (hub pod) image upgraded to 0.8.2
* pod scheduling rules altered to patch current jupyterhub helm bug (jupyterhub/zero-to-jupyterhub-k8s#1282)

### Template updates
* interface templates (deleted index.html in [RhodiumGroup/rhodium-custom-jupyterhub-templates](https://github.com/RhodiumGroup/rhodium-custom-jupyterhub-templates)) so default jupyterhub templates will work for current & dev deployments

### Docker image PR (this one) updates

* unpin & upgrade, then re-pin all dependencies. Notable upgrades:
  * *jupyter*: jupyterlab, jupyterhub, notebook, & all 
  * *dask*: dask, dask_kubernetes, distributed
  * *pydata*: pandas, xarray, numpy, scipy, geopandas
  * *pyviz*: holoviews, geoviews, bokeh, datashader
  * pretty much everything else
* added packages:
  * [ipyleaflet](https://github.com/jupyter-widgets/ipyleaflet) (worth checking out)
  * [sidecar](https://github.com/jupyter-widgets/jupyterlab-sidecar)
* package spec moved to environment file

### CODE REVIEW

**Comment by delgadom** [comment]
Seems there are a number of outstanding issues to hammer out:

* [ ] workers don't seem to spin down
* [ ] mysterious "worker already exists" error
* [ ] `RuntimeError: incompatible bytecode version` encountered when using datashader on a dask cluster
* [ ] autocomplete is populated with everything in globals()

This may take some serious wrangling.

**Comment by delgadom** [comment]
on the plus side, the notebook:octave/octave-worker pairing in the pangeify_octave branch runs beautifully 🙄

**Comment by delgadom** [comment]
Dang. Not sure if you've experienced this but the cells are all slippy (you can scroll down in them) and it looks like the vertical ruler is to blame: https://github.com/jupyterlab/jupyterlab/issues/6836#issuecomment-516054071

Maybe we put off the vertical ruler until this is fixed?

**Comment by delgadom** [comment]
I dunno. maybe not worth delaying deployment though

**Comment by bolliger32** [comment]
oh good catch. yeah i had realized that and was annoyed but didn't realize it was the vertical ruler. I'll take it out of the notebook but leave it in the text editor. super easy fix. I'm working on the octave stuff now. think it's close

**Comment by bolliger32** [comment]
also adding in line numbers for text editor and notebooks by default. we can take them out of notebooks if they are annoying but i think will be useful for scripts at least

**Comment by delgadom** [comment]
superceded by #104

**Pull request closed without merging**
