### PR TITLE
add vertical ruler

### PR DESCRIPTION
**Pull request by bolliger32**
## Summary

Add a file the jupyter reads to override the default setting and set a vertical ruler after 79 characters

### CODE REVIEW

**Comment by delgadom** [comment]
If this looks good when deployed I'd say merge. conda-env-files still has a lot of issues to work through though so it may not see master for a while.

**Comment by bolliger32** [comment]
@delgadom can you deploy 0fecacf on either test or test2? Since I can't do that at the moment. If it works (vertical rulers on both text editor and notebook) then merge away! I also updated travis to deploy to docker any branch that starts with `dev`. I'm currently testing that the regex I used works  on a different branch but will let you know if it fails

**Comment by bolliger32** [comment]
OK - confirmed this travis regex condition works! So once you get a chance to deploy this to test or test2, go ahead and merge!

**Comment by bolliger32** [comment]
addresses #105 (partially). Merging now as it has been tested to work as expected on test-cluster-2. The stability of that cluster is still to be figured out, but these particular features work

**Pull request merged**
